blank_issues_enabled: true
contact_links:
  - name: Discord
    url: https://discord.gg/shapeshift
    about: Join our Discord
  - name: BlackFury Forum
    url: https://forum.shapeshift.com/
    about: Check out the forum
